kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: jenkins-read-secrets-binding
subjects:
- kind: User
  name: jenkins
- kind: ServiceAccount
  name: default
  namespace: jenkins
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
roleRef:
 kind: ClusterRole
 name: jenkins-read-secrets-role
 apiGroup: rbac.authorization.k8s.io